### PR TITLE
Use file-embed to embed data in binary to make deployment easier

### PR DESCRIPTION
**Pull request by albertov**
See #3

### CODE REVIEW

**Comment by ekmett** [comment]
This is something I debated about when I wrote the package originally. 

One reason why I opted against this approach is that it rather greatly expands the size of the resulting executable. There are multiple megabytes worth of hyphenation data. 

With the way things are packaged now you only pay for what you actually use.

I'd be open to building this way with a build flag or something though.

**Comment by albertov** [comment]
Sounds reasonable. I completely overlooked the size of the all the unneeded data files... I've just pushed a commit making `file-embed` optional.

**Comment by albertov** [comment]
@ekmett Is 05ab911 what you had in mind when you said it could be implemented with a build flag?

**Comment by ekmett** [comment]
That looks about right.

**Comment by albertov** [comment]
Thanks!

**Pull request merged**
